In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import os

In [2]:
df= pd.read_csv('C:/Users/LENOVO/Documents/data/Base_Train_Transf.csv', sep=';')
df

Unnamed: 0  PERIODO_1       LLAVE  TARGET  ANTIGUEDAD  \
0                 0     202401  E-44004501       0         262   
1                 1     202310  E-44330401       0          19   
2                 2     202309  E-42434991       0          54   
3                 3     202310  E-71987203       1         115   
4                 4     202310  E-43290482       0         245   
...             ...        ...         ...     ...         ...   
2914667     2914667     202312  E-08773535       0          48   
2914668     2914668     202312  E-15759458       0          29   
2914669     2914669     202312  E-41793902       1          92   
2914670     2914670     202312  E-43338354       0          91   
2914671     2914671     202312  E-70551590       0          28   

         ANTIGUEDAD_rootInv  CUOTA_TOPE_power2  Deuda_PE_BF_rootInv  \
0                  0.061780       1.212289e+06             0.000000   
1                  0.229416       3.894134e+05             0.000000   
2                  0.136083       3.788551e+06             0.000000   
3                  0.093250       1.336267e+06             0.012612   
4                  0.063888       8.575316e+05             0.000000   
...                     ...                ...                  ...   
2914667            0.144338       2.471467e+06             0.000000   
2914668            0.185695       3.783357e+05             0.000000   
2914669            0.104257       2.225766e+04             0.029834   
2914670            0.104828       6.431078e+05             0.008456   
2914671            0.188982       8.684562e+05             0.000000   

         Deuda_PE_SF_U1A_rootInv  Deuda_PE_SF_U6M  ...  RAT_PROV_SAL_TC_log  \
0                       0.000000         0.000000  ...             -0.00334   
1                       0.008899     13549.560000  ...             -0.00334   
2                       0.000000         0.000000  ...              0.00000   
3                       0.014493      6700.815000  ...             -0.00423   
4                       0.000000         0.000000  ...             -0.00666   
...                          ...              ...  ...                  ...   
2914667                 0.000000         0.000000  ...             -0.00334   
2914668                 0.000000         0.000000  ...              0.00157   
2914669                 0.003232     94444.518333  ...             -0.00334   
2914670                 0.006806     22142.903333  ...             -0.00334   
2914671                 0.007474     17550.230000  ...             -0.00334   

         SALDO_CMR  Saldo_TC_rootInv  SCOREPe_mes  SCOREPe_mesMas1  \
0             0.00          0.101885     0.143994         0.139668   
1            19.90          0.108893     0.435933         0.461777   
2             0.00          0.000000     0.184906         0.197249   
3           552.96          0.027510     0.479990         0.454103   
4           264.49          0.125327     0.086052         0.062830   
...            ...               ...          ...              ...   
2914667     820.00          0.063078     0.152911         0.164969   
2914668     496.47          0.037046     0.601930         0.652223   
2914669     531.00          0.173205     0.673838         0.678529   
2914670     429.20          0.087482     0.186164         0.177576   
2914671       0.00          0.100000     0.614038         0.578894   

         SOW_PE_rootInv  SOW_PE_U3M  SOW_TC_U6M  tasaPrepagoBf_power2  \
0              0.000000    0.000000    0.005404                0.0000   
1              0.000000    0.000000    0.004805                0.0000   
2              0.000000    0.000000    0.666667                0.0000   
3              1.000000    1.000000    0.418435                0.0000   
4              0.000000    0.000000    0.058166                0.0000   
...                 ...         ...         ...                   ...   
2914667        0.000000    0.000000    0.075292               

In [3]:
df.drop(['Unnamed: 0','LLAVE'],axis=1,inplace=True)
df

PERIODO_1  TARGET  ANTIGUEDAD  ANTIGUEDAD_rootInv  CUOTA_TOPE_power2  \
0           202401       0         262            0.061780       1.212289e+06   
1           202310       0          19            0.229416       3.894134e+05   
2           202309       0          54            0.136083       3.788551e+06   
3           202310       1         115            0.093250       1.336267e+06   
4           202310       0         245            0.063888       8.575316e+05   
...            ...     ...         ...                 ...                ...   
2914667     202312       0          48            0.144338       2.471467e+06   
2914668     202312       0          29            0.185695       3.783357e+05   
2914669     202312       1          92            0.104257       2.225766e+04   
2914670     202312       0          91            0.104828       6.431078e+05   
2914671     202312       0          28            0.188982       8.684562e+05   

         Deuda_PE_BF_rootInv  Deuda_PE_SF_U1A_rootInv  Deuda_PE_SF_U6M  \
0                   0.000000                 0.000000         0.000000   
1                   0.000000                 0.008899     13549.560000   
2                   0.000000                 0.000000         0.000000   
3                   0.012612                 0.014493      6700.815000   
4                   0.000000                 0.000000         0.000000   
...                      ...                      ...              ...   
2914667             0.000000                 0.000000         0.000000   
2914668             0.000000                 0.000000         0.000000   
2914669             0.029834                 0.003232     94444.518333   
2914670             0.008456                 0.006806     22142.903333   
2914671             0.000000                 0.007474     17550.230000   

         Deuda_PE_SF_U6M_rootInv  Deuda_TC_PE_BF  ...  RAT_PROV_SAL_TC_log  \
0                       0.000000          288.81  ...             -0.00334   
1                       0.008591            0.00  ...             -0.00334   
2                       0.000000            0.00  ...              0.00000   
3                       0.012216         8422.04  ...             -0.00423   
4                       0.000000          127.60  ...             -0.00666   
...                          ...             ...  ...                  ...   
2914667                 0.000000          377.20  ...             -0.00334   
2914668                 0.000000          657.16  ...              0.00157   
2914669                 0.003254         1123.53  ...             -0.00334   
2914670                 0.006720        14180.48  ...             -0.00334   
2914671                 0.007548            0.00  ...             -0.00334   

         SALDO_CMR  Saldo_TC_rootInv  SCOREPe_mes  SCOREPe_mesMas1  \
0             0.00          0.101885     0.143994         0.139668   
1            19.90          0.108893     0.435933         0.461777   
2             0.00          0.000000     0.184906         0.197249   
3           552.96          0.027510     0.479990         0.454103   
4           264.49          0.125327     0.086052         0.062830   
...            ...               ...          ...              ...   
2914667     820.00          0.063078     0.152911         0.164969   
2914668     496.47          0.037046     0.601930         0.652223   
2914669     531.00          0.173205     0.673838         0.678529   
2914670     429.20          0.087482     0.186164         0.177576   
2914671       0.00          0.100000     0.614038         0.578894   

         SOW_PE_rootInv  SOW_PE_U3M  SOW_TC_U6M  tasaPrepagoBf_power2  \
0              0.000000    0.000000    0.005404                0.0000   
1              0.000000    0.000000    0.004805                0.0000   
2              0.000000    0.000000    0.666667                0.0000   
3              1.000000    1.000000    0.418435                0.0000   
4   

In [7]:
print(df['PERIODO_1'].unique())

[202401 202310 202309 202306 202312 202307 202402 202308 202311]


In [9]:
print(df['PERIODO_1'].value_counts())

PERIODO_1
202306    379019
202307    372784
202308    336231
202309    328624
202310    322593
202402    304224
202401    300435
202311    295525
202312    275237
Name: count, dtype: int64


In [14]:
print(df['PERIODO_1'].dtype)

int64


In [16]:
import pandas as pd

df['PERIODO_1'] = df['PERIODO_1'].astype(str).str.strip()
print("Valores únicos en PERIODO_1:", df['PERIODO_1'].unique())

# Filtra las filas con PERIODO_1 == '202306'
df_primero = df[df['PERIODO_1'] == '202306']

# Verifica el resultado
print("Dataset filtrado:")
print(df_primero)


Valores únicos en PERIODO_1: ['202401' '202310' '202309' '202306' '202312' '202307' '202402' '202308'
 '202311']
Dataset filtrado:
        PERIODO_1  TARGET  ANTIGUEDAD  ANTIGUEDAD_rootInv  CUOTA_TOPE_power2  \
6          202306       0           0            0.000000       1.400436e+06   
7          202306       0         111            0.094916       4.184888e+04   
521        202306       0         217            0.067884       1.283394e+06   
522        202306       0          87            0.107211       1.404249e+06   
523        202306       0         115            0.093250       2.938290e+05   
...           ...     ...         ...                 ...                ...   
2914593    202306       0          40            0.158114       4.171275e+06   
2914594    202306       0          95            0.102598       4.159605e+05   
2914595    202306       0           0            0.000000       5.595339e+05   
2914596    202306       0          79            0.112509       2.577

In [17]:
df_primero

PERIODO_1  TARGET  ANTIGUEDAD  ANTIGUEDAD_rootInv  CUOTA_TOPE_power2  \
6          202306       0           0            0.000000       1.400436e+06   
7          202306       0         111            0.094916       4.184888e+04   
521        202306       0         217            0.067884       1.283394e+06   
522        202306       0          87            0.107211       1.404249e+06   
523        202306       0         115            0.093250       2.938290e+05   
...           ...     ...         ...                 ...                ...   
2914593    202306       0          40            0.158114       4.171275e+06   
2914594    202306       0          95            0.102598       4.159605e+05   
2914595    202306       0           0            0.000000       5.595339e+05   
2914596    202306       0          79            0.112509       2.577187e+05   
2914597    202306       0         118            0.092057       6.085560e+05   

         Deuda_PE_BF_rootInv  Deuda_PE_SF_U1A_rootInv  Deuda_PE_SF_U6M  \
6                   0.019190                 0.013685      3931.475000   
7                   0.013245                 0.009054     11948.900000   
521                 0.000000                 0.006462     23944.266667   
522                 0.000000                 0.000000         0.000000   
523                 0.000000                 0.000000         0.000000   
...                      ...                      ...              ...   
2914593             0.000000                 0.000000         0.000000   
2914594             0.000000                 0.000000         0.000000   
2914595             0.000000                 0.026744      1398.130000   
2914596             0.000000                 0.000000         0.000000   
2914597             0.000000                 0.000000         0.000000   

         Deuda_PE_SF_U6M_rootInv  Deuda_TC_PE_BF  ...  RAT_PROV_SAL_TC_log  \
6                       0.015949         2715.61  ...              0.00000   
7                       0.009148         5700.00  ...              0.00056   
521                     0.006462         1277.39  ...              0.00406   
522                     0.000000          679.46  ...              0.07575   
523                     0.000000         2249.36  ...              0.00112   
...                          ...             ...  ...                  ...   
2914593                 0.000000         1267.30  ...              0.03675   
2914594                 0.000000          288.80  ...             -0.00414   
2914595                 0.026744            0.00  ...              0.00000   
2914596                 0.000000          450.00  ...             -0.00636   
2914597                 0.000000           59.80  ...             -0.00096   

         SALDO_CMR  Saldo_TC_rootInv  SCOREPe_mes  SCOREPe_mesMas1  \
6             0.00          0.000000          0.0         0.273276   
7           173.29          0.052200          0.0         0.735067   
521        2472.93          0.021502          0.0         0.345962   
522         771.97          0.047036          0.0         0.249352   
523         310.54          0.023925          0.0         0.441586   
...            ...               ...          ...              ...   
2914593     175.61          0.048057          0.0         0.196237   
2914594       0.00          0.060193          0.0         0.094711   
2914595       0.00          0.000000          0.0         0.411720   
2914596     973.86          0.078087          0.0         0.398023   
2914597     279.30          0.102240          0.0         0.240190   

         SOW_PE_rootInv  SOW_PE_U3M  SOW_TC_U6M  tasaPrepagoBf_power2  \
6              1.000000    1.000000    0.000003                0.0000   
7              1.678014    0.118383    0.251366              863.1844   
521            0.000000    0.000000    0.213777                0.0000   
522            0.000000    0.000000    1.000000                0.0000   
523            

In [18]:
print(df_primero['TARGET'].value_counts())

TARGET
0    360782
1     18237
Name: count, dtype: int64


In [19]:
df_segundo = df[df['PERIODO_1'] == '202307']
df_segundo

PERIODO_1  TARGET  ANTIGUEDAD  ANTIGUEDAD_rootInv  CUOTA_TOPE_power2  \
9          202307       0           8            0.353553       5.118454e+06   
10         202307       0           0            0.000000       4.950536e+06   
11         202307       0          52            0.138675       4.387738e+05   
12         202307       0          60            0.129099       1.313660e+06   
13         202307       0          74            0.116248       7.039042e+05   
...           ...     ...         ...                 ...                ...   
2861665    202307       0         257            0.062378       1.380766e+06   
2861666    202307       0         222            0.067116       1.167415e+06   
2861667    202307       0         116            0.092848       3.214849e+06   
2861668    202307       0          81            0.111111       3.315604e+06   
2861669    202307       0         249            0.063372       3.024956e+06   

         Deuda_PE_BF_rootInv  Deuda_PE_SF_U1A_rootInv  Deuda_PE_SF_U6M  \
9                   0.000000                 0.018332      2975.748333   
10                  0.009323                 0.005512     28862.830000   
11                  0.000000                 0.035083         0.000000   
12                  0.000000                 0.000000         0.000000   
13                  0.000000                 0.000000         0.000000   
...                      ...                      ...              ...   
2861665             0.000000                 0.000000         0.000000   
2861666             0.000000                 0.000000         0.000000   
2861667             0.000000                 0.008972      9295.923333   
2861668             0.000000                 0.000000         0.000000   
2861669             0.000000                 0.000000         0.000000   

         Deuda_PE_SF_U6M_rootInv  Deuda_TC_PE_BF  ...  RAT_PROV_SAL_TC_log  \
9                       0.018332          647.42  ...             -0.00235   
10                      0.005886        14796.23  ...              0.00296   
11                      0.000000          712.93  ...              0.00594   
12                      0.000000            0.00  ...              0.00000   
13                      0.000000          218.77  ...              0.00311   
...                          ...             ...  ...                  ...   
2861665                 0.000000          744.03  ...              0.00213   
2861666                 0.000000            0.00  ...             -0.00334   
2861667                 0.010372         1544.70  ...              0.00474   
2861668                 0.000000          673.30  ...             -0.01957   
2861669                 0.000000         4265.35  ...              0.00419   

         SALDO_CMR  Saldo_TC_rootInv  SCOREPe_mes  SCOREPe_mesMas1  \
9          675.440          0.037494     0.000000         0.604124   
10        3838.975          0.015295     0.000000         0.769532   
11         884.750          0.033414     0.000000         0.812886   
12           0.000          0.000000     0.043698         0.042920   
13         302.540          0.045596     0.282505         0.305826   
...            ...               ...          ...              ...   
2861665   1532.210          0.047965     0.143082         0.150650   
2861666      0.000          0.070071     0.180351         0.181748   
2861667   2066.450          0.013641     0.303094         0.295267   
2861668   1782.040          0.048002     0.078879         0.128000   
2861669   1953.080          0.021382     0.183141         0.203432   

         SOW_PE_rootInv  SOW_PE_U3M  SOW_TC_U6M  tasaPrepagoBf_power2  \
9              0.000000    0.000000    0.372153                  0.00   
10             1.471659    0.459831    0.782944               1505.44   
11             0.000000    0.000000    0.247633                  0.00   
12             0.000000    0.000000    0.000000                  0.00   
13             

In [20]:
print(df_segundo['TARGET'].value_counts())

TARGET
0    355725
1     17059
Name: count, dtype: int64


In [23]:
df_tercero = df[df['PERIODO_1'] == '202308']
print(df_tercero['TARGET'].value_counts())

TARGET
0    320033
1     16198
Name: count, dtype: int64


In [24]:
df_cuarto = df[df['PERIODO_1'] == '202309']
print(df_cuarto['TARGET'].value_counts())

TARGET
0    309294
1     19330
Name: count, dtype: int64


In [25]:
df_quinto = df[df['PERIODO_1'] == '202310']
print(df_quinto['TARGET'].value_counts())

TARGET
0    303910
1     18683
Name: count, dtype: int64


In [26]:
df_sexto = df[df['PERIODO_1'] == '202311']
print(df_sexto['TARGET'].value_counts())

TARGET
0    278905
1     16620
Name: count, dtype: int64


In [27]:
df_septimo = df[df['PERIODO_1'] == '202312']
print(df_septimo['TARGET'].value_counts())

TARGET
0    261359
1     13878
Name: count, dtype: int64


In [28]:
df_octavo = df[df['PERIODO_1'] == '202402']
print(df_octavo['TARGET'].value_counts())

TARGET
0    287990
1     16234
Name: count, dtype: int64


In [29]:
df_noveno = df[df['PERIODO_1'] == '202401']
print(df_noveno['TARGET'].value_counts())

TARGET
0    284609
1     15826
Name: count, dtype: int64


In [4]:
df.drop(['PERIODO_1'],axis=1,inplace=True)
df

TARGET  ANTIGUEDAD  ANTIGUEDAD_rootInv  CUOTA_TOPE_power2  \
0             0         262            0.061780       1.212289e+06   
1             0          19            0.229416       3.894134e+05   
2             0          54            0.136083       3.788551e+06   
3             1         115            0.093250       1.336267e+06   
4             0         245            0.063888       8.575316e+05   
...         ...         ...                 ...                ...   
2914667       0          48            0.144338       2.471467e+06   
2914668       0          29            0.185695       3.783357e+05   
2914669       1          92            0.104257       2.225766e+04   
2914670       0          91            0.104828       6.431078e+05   
2914671       0          28            0.188982       8.684562e+05   

         Deuda_PE_BF_rootInv  Deuda_PE_SF_U1A_rootInv  Deuda_PE_SF_U6M  \
0                   0.000000                 0.000000         0.000000   
1                   0.000000                 0.008899     13549.560000   
2                   0.000000                 0.000000         0.000000   
3                   0.012612                 0.014493      6700.815000   
4                   0.000000                 0.000000         0.000000   
...                      ...                      ...              ...   
2914667             0.000000                 0.000000         0.000000   
2914668             0.000000                 0.000000         0.000000   
2914669             0.029834                 0.003232     94444.518333   
2914670             0.008456                 0.006806     22142.903333   
2914671             0.000000                 0.007474     17550.230000   

         Deuda_PE_SF_U6M_rootInv  Deuda_TC_PE_BF  Deuda_TC_PE_BF_log  ...  \
0                       0.000000          288.81             5.66923  ...   
1                       0.008591            0.00             0.00000  ...   
2                       0.000000            0.00             0.00000  ...   
3                       0.012216         8422.04             9.03873  ...   
4                       0.000000          127.60             4.85671  ...   
...                          ...             ...                 ...  ...   
2914667                 0.000000          377.20             5.93542  ...   
2914668                 0.000000          657.16             6.48945  ...   
2914669                 0.003254         1123.53             7.02512  ...   
2914670                 0.006720        14180.48             9.55969  ...   
2914671                 0.007548            0.00             0.00000  ...   

         RAT_PROV_SAL_TC_log  SALDO_CMR  Saldo_TC_rootInv  SCOREPe_mes  \
0                   -0.00334       0.00          0.101885     0.143994   
1                   -0.00334      19.90          0.108893     0.435933   
2                    0.00000       0.00          0.000000     0.184906   
3                   -0.00423     552.96          0.027510     0.479990   
4                   -0.00666     264.49          0.125327     0.086052   
...                      ...        ...               ...          ...   
2914667             -0.00334     820.00          0.063078     0.152911   
2914668              0.00157     496.47          0.037046     0.601930   
2914669             -0.00334     531.00          0.173205     0.673838   
2914670             -0.00334     429.20          0.087482     0.186164   
2914671             -0.00334       0.00          0.100000     0.614038   

         SCOREPe_mesMas1  SOW_PE_rootInv  SOW_PE_U3M  SOW_TC_U6M  \
0               0.139668        0.000000    0.000000    0.005404   
1               0.461777        0.000000    0.000000    0.004805   
2               0.197249        0.000000    0.000000    0.666667   
3               0.454103        1.000000    1.000000    0.418435   
4               0.062830        0.000000    0.000000    0.058166   
...                  ...             ...         ...     

In [5]:
X=df
X=X.drop(['TARGET'],axis=1)
X

ANTIGUEDAD  ANTIGUEDAD_rootInv  CUOTA_TOPE_power2  \
0               262            0.061780       1.212289e+06   
1                19            0.229416       3.894134e+05   
2                54            0.136083       3.788551e+06   
3               115            0.093250       1.336267e+06   
4               245            0.063888       8.575316e+05   
...             ...                 ...                ...   
2914667          48            0.144338       2.471467e+06   
2914668          29            0.185695       3.783357e+05   
2914669          92            0.104257       2.225766e+04   
2914670          91            0.104828       6.431078e+05   
2914671          28            0.188982       8.684562e+05   

         Deuda_PE_BF_rootInv  Deuda_PE_SF_U1A_rootInv  Deuda_PE_SF_U6M  \
0                   0.000000                 0.000000         0.000000   
1                   0.000000                 0.008899     13549.560000   
2                   0.000000                 0.000000         0.000000   
3                   0.012612                 0.014493      6700.815000   
4                   0.000000                 0.000000         0.000000   
...                      ...                      ...              ...   
2914667             0.000000                 0.000000         0.000000   
2914668             0.000000                 0.000000         0.000000   
2914669             0.029834                 0.003232     94444.518333   
2914670             0.008456                 0.006806     22142.903333   
2914671             0.000000                 0.007474     17550.230000   

         Deuda_PE_SF_U6M_rootInv  Deuda_TC_PE_BF  Deuda_TC_PE_BF_log  \
0                       0.000000          288.81             5.66923   
1                       0.008591            0.00             0.00000   
2                       0.000000            0.00             0.00000   
3                       0.012216         8422.04             9.03873   
4                       0.000000          127.60             4.85671   
...                          ...             ...                 ...   
2914667                 0.000000          377.20             5.93542   
2914668                 0.000000          657.16             6.48945   
2914669                 0.003254         1123.53             7.02512   
2914670                 0.006720        14180.48             9.55969   
2914671                 0.007548            0.00             0.00000   

         Deuda_TC_PE_SF_log  ...  RAT_PROV_SAL_TC_log  SALDO_CMR  \
0                   9.09476  ...             -0.00334       0.00   
1                  10.25907  ...             -0.00334      19.90   
2                   3.77391  ...              0.00000       0.00   
3                   9.11684  ...             -0.00423     552.96   
4                   7.41883  ...             -0.00666     264.49   
...                     ...  ...                  ...        ...   
2914667             9.40875  ...             -0.00334     820.00   
2914668            10.31177  ...              0.00157     496.47   
2914669            11.40744  ...             -0.00334     531.00   
2914670             9.90292  ...             -0.00334     429.20   
2914671             9.66418  ...             -0.00334       0.00   

         Saldo_TC_rootInv  SCOREPe_mes  SCOREPe_mesMas1  SOW_PE_rootInv  \
0                0.101885     0.143994         0.139668        0.000000   
1                0.108893     0.435933         0.461777        0.000000   
2                0.000000     0.184906         0.197249        0.000000   
3                0.027510     0.479990         0.454103        1.000000   
4                0.125327     0.086052         0.062830        0.000000   
...                   ...          ...              ...             ...   
2914667          0.063078     0.152911         0.164969        0.000000   
2914668          0.037046     0.601930         0.652223        0.000000   
2914669          0

In [6]:
Y=df["TARGET"]
Y

0          0
1          0
2          0
3          1
4          0
          ..
2914667    0
2914668    0
2914669    1
2914670    0
2914671    0
Name: TARGET, Length: 2914672, dtype: int64

In [34]:
print(Y.value_counts())

TARGET
0    2762607
1     152065
Name: count, dtype: int64


In [38]:
X.isnull().sum()

ANTIGUEDAD                             0
ANTIGUEDAD_rootInv                     0
CUOTA_TOPE_power2                      0
Deuda_PE_BF_rootInv                    0
Deuda_PE_SF_U1A_rootInv                0
Deuda_PE_SF_U6M                        0
Deuda_PE_SF_U6M_rootInv                0
Deuda_TC_PE_BF                         0
Deuda_TC_PE_BF_log                     0
Deuda_TC_PE_SF_log                     0
Deuda_TC_SF_U3M                        0
DISPONIBLE_FINAL_SC_RED                0
DISPONIBLE_FINAL_SC_RED_log            0
DISPONIBLE_FINAL_SC_RED_rootInv        0
EDAD                                   0
LINEACREDITO_rootInv                   0
montodesembolsoPE_rootInv              0
MONTOSOLES_onTHEM                      0
MONTOSOLES_onTHEM_rootInv              0
n_desembolsosPE                        0
PromDesembolsou12m_PE                  0
PromDesembolsou3A_PE                   0
PromDesembolsou6m_PE                   0
PromDesembolsou6m_PE_log               0
PROVISION_TOTAL_

In [7]:
from sklearn.impute import SimpleImputer
import pandas as pd

# Crear el imputador para la media
imputer = SimpleImputer(strategy='mean')

# Imputar los valores faltantes en la columna específica
X['RAT_PROV_SAL_TC_log'] = imputer.fit_transform(X[['RAT_PROV_SAL_TC_log']])

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [41]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, precision_recall_curve
from imblearn.over_sampling import SMOTE  # Para manejar desbalance
from sklearn.model_selection import GridSearchCV
import numpy as np

# Paso 1: Manejar el desbalance con SMOTE
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

# Paso 2: Crear y ajustar el modelo XGBClassifier con parámetros mejorados
model = XGBClassifier(
    objective='binary:logistic',
    max_depth=5,  # Reduce la profundidad para evitar sobreajuste
    learning_rate=0.1,  # Reduce el learning rate para mejorar la convergencia
    n_estimators=200,  # Más árboles para mayor capacidad
    scale_pos_weight=len(y_train_resampled[y_train_resampled == 0]) / len(y_train_resampled[y_train_resampled == 1]),  # Manejar desbalance
    random_state=42
)

# Entrenar el modelo
model.fit(X_train_resampled, y_train_resampled)

# Predecir probabilidades
y_proba = model.predict_proba(X_test)[:, 1]

# Paso 3: Ajustar el umbral de decisión
optimal_threshold = 0.3  # Ajusta este valor después de analizar las métricas
y_pred = (y_proba >= optimal_threshold).astype(int)

# Paso 4: Evaluar el modelo
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.4f}')

print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))

print('Classification Report:')
print(classification_report(y_test, y_pred))

# Paso 5: Curva de precisión-recall para encontrar el mejor umbral (opcional)
precision, recall, thresholds = precision_recall_curve(y_test, y_proba)

# Encontrar el umbral que maximiza el F1-score
f1_scores = 2 * (precision * recall) / (precision + recall)
optimal_idx = np.argmax(f1_scores)
optimal_threshold = thresholds[optimal_idx]
print(f'Mejor umbral para F1-score: {optimal_threshold:.2f}')


Accuracy: 0.8779
Confusion Matrix:
[[494506  57746]
 [ 13432  17251]]
Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.90      0.93    552252
           1       0.23      0.56      0.33     30683

    accuracy                           0.88    582935
   macro avg       0.60      0.73      0.63    582935
weighted avg       0.93      0.88      0.90    582935

Mejor umbral para F1-score: 0.99


C:\Users\LENOVO\AppData\Local\Temp\ipykernel_1652\3863724382.py:45: RuntimeWarning: invalid value encountered in divide
  f1_scores = 2 * (precision * recall) / (precision + recall)


In [42]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, precision_recall_curve
from imblearn.over_sampling import SMOTE  # Para manejar desbalance
from sklearn.model_selection import train_test_split
import numpy as np

# Paso 1: Manejar el desbalance con SMOTE
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

# Paso 2: Crear y ajustar el modelo XGBClassifier con parámetros mejorados
model = XGBClassifier(
    objective='binary:logistic',
    max_depth=5,  # Reduce la profundidad para evitar sobreajuste
    learning_rate=0.1,  # Reduce el learning rate para mejorar la convergencia
    n_estimators=200,  # Más árboles para mayor capacidad
    scale_pos_weight=len(y_train_resampled[y_train_resampled == 0]) / len(y_train_resampled[y_train_resampled == 1]),  # Manejar desbalance
    random_state=42
)

# Entrenar el modelo
model.fit(X_train_resampled, y_train_resampled)

# Predecir probabilidades
y_proba = model.predict_proba(X_test)[:, 1]

# Paso 3: Ajustar el umbral de decisión
optimal_threshold = 0.3  # Ajusta este valor después de analizar las métricas
y_pred = (y_proba >= optimal_threshold).astype(int)

# Paso 4: Evaluar el modelo
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.4f}')

print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))

print('Classification Report:')
print(classification_report(y_test, y_pred))

# Paso 5: Curva de precisión-recall para encontrar el mejor umbral
precision, recall, thresholds = precision_recall_curve(y_test, y_proba)

# Calcular el F1-score de manera segura
f1_scores = np.where((precision + recall) == 0, 0, 2 * (precision * recall) / (precision + recall))

# Encontrar el índice del umbral que maximiza el F1-score
optimal_idx = np.argmax(f1_scores)
optimal_threshold = thresholds[optimal_idx]
print(f'Mejor umbral para F1-score: {optimal_threshold:.2f}')

# Paso 6: Recalcular predicciones con el mejor umbral
y_pred_optimal = (y_proba >= optimal_threshold).astype(int)

# Evaluar el modelo con el nuevo umbral
accuracy_optimal = accuracy_score(y_test, y_pred_optimal)
print(f'Accuracy con mejor umbral: {accuracy_optimal:.4f}')

print('Confusion Matrix con mejor umbral:')
print(confusion_matrix(y_test, y_pred_optimal))

print('Classification Report con mejor umbral:')
print(classification_report(y_test, y_pred_optimal))


Accuracy: 0.8779
Confusion Matrix:
[[494506  57746]
 [ 13432  17251]]
Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.90      0.93    552252
           1       0.23      0.56      0.33     30683

    accuracy                           0.88    582935
   macro avg       0.60      0.73      0.63    582935
weighted avg       0.93      0.88      0.90    582935

Mejor umbral para F1-score: 0.43
Accuracy con mejor umbral: 0.9126
Confusion Matrix con mejor umbral:
[[518770  33482]
 [ 17470  13213]]
Classification Report con mejor umbral:


C:\Users\LENOVO\AppData\Local\Temp\ipykernel_1652\840984410.py:45: RuntimeWarning: invalid value encountered in divide
  f1_scores = np.where((precision + recall) == 0, 0, 2 * (precision * recall) / (precision + recall))


              precision    recall  f1-score   support

           0       0.97      0.94      0.95    552252
           1       0.28      0.43      0.34     30683

    accuracy                           0.91    582935
   macro avg       0.63      0.69      0.65    582935
weighted avg       0.93      0.91      0.92    582935



In [43]:
# Guardar el modelo entrenado
model.save_model("xgb_model.json")

In [45]:
from xgboost import XGBClassifier

# Cargar el modelo previamente guardado
loaded_model = XGBClassifier()
loaded_model.load_model("xgb_model.json")
# Suponiendo que tienes un nuevo dataset llamado `X_new`
y_new_proba = loaded_model.predict_proba(X)[:, 1]

# Aplicar el umbral óptimo para clasificar
optimal_threshold = 0.3  # Usa el umbral calculado previamente
y_new_pred = (y_new_proba >= optimal_threshold).astype(int)

# Mostrar resultados
print("Predicciones:", y_new_pred)


Predicciones: [0 0 0 ... 1 1 0]


In [47]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Supongamos que tienes las etiquetas reales `y_new` para el nuevo dataset
# Ejemplo: y_new = [0, 1, 0, 1, 0, ...]  # Debes tener las etiquetas verdaderas

# Comparar precisión
accuracy = accuracy_score(y_new_pred, Y)
print(f'Accuracy: {accuracy:.4f}')

# Matriz de confusión
print('Confusion Matrix:')
print(confusion_matrix(y_new_pred, Y))

# Reporte de clasificación
print('Classification Report:')
print(classification_report(y_new_pred, Y))


Accuracy: 0.8787
Confusion Matrix:
[[2474901   65701]
 [ 287706   86364]]
Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.97      0.93   2540602
           1       0.57      0.23      0.33    374070

    accuracy                           0.88   2914672
   macro avg       0.73      0.60      0.63   2914672
weighted avg       0.85      0.88      0.86   2914672



In [48]:
from xgboost import XGBClassifier

#Crear el modelo XGBClassifier
model = XGBClassifier(
    objective='binary:logistic',
    max_depth=6,
    learning_rate=0.3,
    n_estimators=100,
    random_state=42
)

#Entrenar el modelo
model.fit(X_train, y_train)
#solo usar cuando es una matriz 
y_pred = model.predict(X_test)

#Para XGBClassifier se requiere redondear los resultados si es un problema binario
y_pred = [1 if y > 0.5 else 0 for y in y_pred]  # Si estás usando clasificación

#Calcular la precisión y otras métricas
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.4f}')

#Matriz de confusión y reporte de clasificación
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))

print('Classification Report:')
print(classification_report(y_test, y_pred))

Accuracy: 0.9497
Confusion Matrix:
[[550004   2248]
 [ 27095   3588]]
Classification Report:
              precision    recall  f1-score   support

           0       0.95      1.00      0.97    552252
           1       0.61      0.12      0.20     30683

    accuracy                           0.95    582935
   macro avg       0.78      0.56      0.59    582935
weighted avg       0.94      0.95      0.93    582935



In [50]:
from xgboost import XGBClassifier

#Crear el modelo XGBClassifier
model = XGBClassifier(
    objective='binary:logistic',
    max_depth=6,# produnfidad de los arboles
    learning_rate=0.3, #tasa de aprendizaje 
    n_estimators=1000,# nuermo de arboles
    random_state=42
)

#Entrenar el modelo
model.fit(X_train, y_train)
#solo usar cuando es una matriz 
y_pred = model.predict(X_test)

#Para XGBClassifier se requiere redondear los resultados si es un problema binario
y_pred = [1 if y > 0.5 else 0 for y in y_pred]  # Si estás usando clasificación

#Calcular la precisión y otras métricas
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.4f}')

#Matriz de confusión y reporte de clasificación
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))

print('Classification Report:')
print(classification_report(y_test, y_pred))

Accuracy: 0.9522
Confusion Matrix:
[[549003   3249]
 [ 24640   6043]]
Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.99      0.98    552252
           1       0.65      0.20      0.30     30683

    accuracy                           0.95    582935
   macro avg       0.80      0.60      0.64    582935
weighted avg       0.94      0.95      0.94    582935



In [53]:
from xgboost import XGBClassifier

#Crear el modelo XGBClassifier
model = XGBClassifier(
    objective='binary:logistic',
    max_depth=6,# produnfidad de los arboles
    learning_rate=0.3, #tasa de aprendizaje 
    n_estimators=4000,# nuermo de arboles
    random_state=42
)

#Entrenar el modelo
model.fit(X_train, y_train)
#solo usar cuando es una matriz 
y_pred = model.predict(X_test)

#Para XGBClassifier se requiere redondear los resultados si es un problema binario
y_pred = [1 if y > 0.5 else 0 for y in y_pred]  # Si estás usando clasificación

#Calcular la precisión y otras métricas
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.4f}')

#Matriz de confusión y reporte de clasificación
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))

print('Classification Report:')
print(classification_report(y_test, y_pred))

Accuracy: 0.9552
Confusion Matrix:
[[548351   3901]
 [ 22203   8480]]
Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.99      0.98    552252
           1       0.68      0.28      0.39     30683

    accuracy                           0.96    582935
   macro avg       0.82      0.63      0.69    582935
weighted avg       0.95      0.96      0.95    582935



In [65]:
from xgboost import XGBClassifier

#Crear el modelo XGBClassifier
model = XGBClassifier(
    objective='binary:logistic',
    max_depth=6,# produnfidad de los arboles
    learning_rate=0.3, #tasa de aprendizaje 
    n_estimators=10000,# nuermo de arboles
    random_state=42
)

#Entrenar el modelo
model.fit(X_train, y_train)
#solo usar cuando es una matriz 
y_pred = model.predict(X_test)

#Para XGBClassifier se requiere redondear los resultados si es un problema binario
y_pred = [1 if y > 0.5 else 0 for y in y_pred]  # Si estás usando clasificación

#Calcular la precisión y otras métricas
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.4f}')

#Matriz de confusión y reporte de clasificación
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))

print('Classification Report:')
print(classification_report(y_test, y_pred))

Accuracy: 0.9572
Confusion Matrix:
[[548398   3854]
 [ 21118   9565]]
Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.99      0.98    552252
           1       0.71      0.31      0.43     30683

    accuracy                           0.96    582935
   macro avg       0.84      0.65      0.71    582935
weighted avg       0.95      0.96      0.95    582935



In [66]:
from xgboost import XGBClassifier

#Crear el modelo XGBClassifier
model = XGBClassifier(
    objective='binary:logistic',
    max_depth=6,# produnfidad de los arboles
    learning_rate=0.3, #tasa de aprendizaje 
    n_estimators=20000,# nuermo de arboles
    random_state=42
)

#Entrenar el modelo
model.fit(X_train, y_train)
#solo usar cuando es una matriz 
y_pred = model.predict(X_test)

#Para XGBClassifier se requiere redondear los resultados si es un problema binario
y_pred = [1 if y > 0.5 else 0 for y in y_pred]  # Si estás usando clasificación

#Calcular la precisión y otras métricas
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.4f}')

#Matriz de confusión y reporte de clasificación
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))

print('Classification Report:')
print(classification_report(y_test, y_pred))

Accuracy: 0.9583
Confusion Matrix:
[[548451   3801]
 [ 20483  10200]]
Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.99      0.98    552252
           1       0.73      0.33      0.46     30683

    accuracy                           0.96    582935
   macro avg       0.85      0.66      0.72    582935
weighted avg       0.95      0.96      0.95    582935



In [9]:
from xgboost import XGBClassifier

#Crear el modelo XGBClassifier
model = XGBClassifier(
    objective='binary:logistic',
    max_depth=6,# produnfidad de los arboles
    learning_rate=0.3, #tasa de aprendizaje 
    n_estimators=25000,# nuermo de arboles
    random_state=42
)

#Entrenar el modelo
model.fit(X_train, y_train)
#solo usar cuando es una matriz 
y_pred = model.predict(X_test)

#Para XGBClassifier se requiere redondear los resultados si es un problema binario
y_pred = [1 if y > 0.5 else 0 for y in y_pred]  # Si estás usando clasificación

#Calcular la precisión y otras métricas
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.4f}')

#Matriz de confusión y reporte de clasificación
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))

54
print('Classification Report:')
print(classification_report(y_test, y_pred))

NameError: name 'accuracy_score' is not defined